project:
  type: website

website:
  title: "Website 2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: source-1.qmd
        text: Source 1
      - href: source-2.qmd
        text: Source 2 

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



